### ISSUE TITLE
Markup of blog title and description has to be corrected

### ISSUE THREAD

**Issue by ihvou** [ihvou/sitepie#10]
currently 
<img width="390" alt="screen shot 2018-07-26 at 7 11 46 pm" src="https://user-images.githubusercontent.com/5359664/43274412-cda2b9b2-9107-11e8-9d91-136bab9b6cc8.png">

here is how it should be
<img width="503" alt="screen shot 2018-07-26 at 7 10 59 pm" src="https://user-images.githubusercontent.com/5359664/43274422-d60ceb9a-9107-11e8-8864-08d280344f68.png">

**Comment by answer3** [comment]
1 - from mockup
2 - from generator
All the same
<img width="263" alt="screen shot 2018-07-30 at 11 47 31 pm" src="https://user-images.githubusercontent.com/9967358/43425487-0b35b330-9453-11e8-8137-6a37e6961188.png">
<img width="273" alt="screen shot 2018-07-30 at 11 47 43 pm" src="https://user-images.githubusercontent.com/9967358/43425496-11149802-9453-11e8-837d-7f23bd7eee9d.png">
