### ISSUE TITLE
Broken tag link from blog description at post page 

### ISSUE THREAD

**Issue by ihvou** [ihvou/sitepie#12]
<img width="378" alt="screen shot 2018-07-26 at 7 30 59 pm" src="https://user-images.githubusercontent.com/5359664/43275467-8a1ec908-910a-11e8-889e-00a83b40d440.png">
from here

**Comment by answer3** [comment]
Fixed
But we have a new issue
<img width="906" alt="screen shot 2018-07-30 at 11 52 39 pm" src="https://user-images.githubusercontent.com/9967358/43425722-c3d0c92a-9453-11e8-849f-34644c396c4d.png">
Need to fix list markup
