### ISSUE TITLE
Stand along generator version. Clean repository 

### ISSUE THREAD

**Issue by ihvou** [ihvou/sitepie#14]
1. make necessary adjustments to make possible to develop/upgrade "cli based generator" independently from: spreadsheet module; admin 
- spreadsheet module should produce csv file. cli based generator should work with file as the only incoming data source
2. clear this repository leaving here only "cli based generator" with templates and csv sample
3. make repository has everything necessary for contributor to download project and play/test it locally

**Comment by answer3** [comment]
ready
