### ISSUE TITLE
Ad markup is broken at post page

### ISSUE THREAD

**Issue by ihvou** [ihvou/sitepie#4]
<img width="334" alt="screen shot 2018-07-26 at 6 42 21 pm" src="https://user-images.githubusercontent.com/5359664/43272969-ecb2ba36-9103-11e8-9a53-204c9650fc1b.png">
- the way it looks

<img width="337" alt="screen shot 2018-07-26 at 6 44 05 pm" src="https://user-images.githubusercontent.com/5359664/43272980-f37f4b7c-9103-11e8-91b3-75c5deeccc15.png">
that's how it should look

**Comment by answer3** [comment]
fixed
