### ISSUE TITLE
Markup of post description needs to be corrected 

### ISSUE THREAD

**Issue by ihvou** [ihvou/sitepie#9]
check mockup please 
font sizes, text paddings, font color and icon color
<img width="435" alt="screen shot 2018-07-26 at 6 52 47 pm" src="https://user-images.githubusercontent.com/5359664/43273507-43881404-9105-11e8-81f7-b7945e414cb3.png">

**Comment by answer3** [comment]
1 - from mockup
2 - from generator
<img width="620" alt="screen shot 2018-07-30 at 11 43 15 pm" src="https://user-images.githubusercontent.com/9967358/43425356-ae5f0328-9452-11e8-8434-143c99dfa11c.png">
<img width="344" alt="screen shot 2018-07-30 at 11 44 18 pm" src="https://user-images.githubusercontent.com/9967358/43425364-b5b1c0e8-9452-11e8-87cf-912fb662e32f.png">

The same styles
